all assets clean:
	make -C finding_notes_played_general_idea_assets "$@"
	make -C finding_when_notes_are_played_assets "$@"
	make -C intro_assets "$@"
	make -C issue_with_tied_notes_assets "$@"
	make -C issue_with_grace_notes_assets "$@"
	make -C issue_with_repeats_assets "$@"
	make -C issue_with_overlapping_notes_assets "$@"
	make -C issue_with_repeated_notes_assets "$@"
	make -C finding_systems_top_and_bottom_assets "$@"
	make -C finding_on_which_stave_a_note_is_assets "$@"
	make -C finding_the_staff_instrument_name_assets "$@"

.PHONY: clean assets all
